name: "web-app"
mode: "dev"
version: "v0.1"

host: 127.0.0.1
port: 8080


start_time: "2023-5-29"
machine_id: 1

jwt_access_expire: 2592000
jwt_refresh_expire: 2592000

log:
  level: "INFO"
  filename: "./log/web-app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  compress: false

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "Zy_9908091729"
  dbname: "bluebell"
  max_life_time: 10
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: "Zy_9908091729"
  db: 0
  pool_size: 100


